language: python
dist: xenial
sudo: false
python:
  - "3.7"
  - "3.8"
  - "3.9"
env:
  global:
    - MODULE=pynndescent
  matrix:
    - COVERAGE="false"
install: source ci/install.sh
script: bash ci/test.sh
after_success: source ci/success.sh